# Generated by Django 5.0.2 on 2024-02-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_rename_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tags',
            field=models.CharField(default='', max_length=50),
        ),
    ]
